{
 "title": "Golden Signals",
 "description": "Golden Signals of services",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Service", "query": { "query": "label_values(target_info,job)" } }
  ]
 },
 "panels": [
  { "title": "Traffic Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Latency (p50 / p95 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum(rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\"}[5m])) by (le)\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\"}[5m])) by (le)\r\n)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\"}[5m])) by (le)\r\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  (\r\n    sum(rate(http_server_requests_seconds_count{service_name=~\"$service_name\",status=~\"5..\"}[5m]))\r\n    /\r\n    sum(rate(http_server_requests_seconds_count{service_name=~\"$service_name\"}[5m]))\r\n  ) \r\nor vector(0)\r\n)",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Inbound Bulkhead Permits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{service_name=~\"$service_name\", name=\"webBulkheadFilter\"}",
     "legendFormat": "MAX_ALLOWED"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{service_name=~\"$service_name\", name=\"webBulkheadFilter\"} - resilience4j_bulkhead_available_concurrent_calls{service_name=~\"$service_name\", name=\"webBulkheadFilter\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Traffic (RPS)",
   "type": "timeseries",
   "description": "Traffic Requests/second",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service_name=~\"$service_name\"}[1m]))",
     "legendFormat": "req/sec"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "description": "The total number of platform threads currently alive in the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{service_name=~\"$service_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Daemon threads",
   "type": "timeseries",
   "description": "Background threads. Do not keep the JVM alive. Ex GC helpers, schedulers, async internals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{service_name=~\"$service_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "timeseries",
   "description": "The maximum number of live threads ever observed since JVM start. This value never goes down until restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{service_name=~\"$service_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "description": "Threads by JVM state.\n\nRUNNABLE: Actively executing or ready to run.\n\nBLOCKED: Waiting for a monitor lock.\n\nWAITING: Waiting indefinitely (park, wait).\n\nTIMED_WAITING: Waiting with a timeout.\n\nNEW: Created but not started.\n\nTERMINATED: Finished execution.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{service_name=~\"$service_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}